playbook:
  owner: "luixo"
  repo: "mac-playbook"
dockutil_install: true
dockitems_persist:
  - name: Arc
    path: /Applications/Arc.app/
    pos: 1
  - name: iTerm
    path: /Applications/iTerm.app/
    pos: 2
  - name: Telegram
    path: /Applications/Telegram.app/
    pos: 3
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app/
    pos: 4
  - name: Activity Monitor
    path: /System/Applications/Utilities/Activity Monitor.app/
    pos: 5
  - name: System Settings
    path: /System/Applications/System Settings.app/
    pos: 6
  - name: Calendar
    path: /System/Applications/Calendar.app/
    pos: 7
  - name: Todoist
    path: /Applications/Todoist.app/
    pos: 8
  - name: Slack
    path: /Applications/Slack.app/
    pos: 9
  - name: Notes
    path: /System/Applications/Notes.app/
    pos: 910
